[package]
name = "librus-api"
version = "1.0.0"
edition = "2021"


[dependencies]
reqwest = "0.11.22"
futures = "0.3" # for our async / await blocks
tokio = { version = "1.12.0", features = ["full"] } # for our async runtime
